In [11]:
from l0pca import sampling
import numpy as np
import tensorflow as tf

In [86]:
import numpy as np
import tensorflow as tf
data = np.loadtxt('Buettner2015Features.csv', delimiter=',', dtype='object')
gene_names = data[0, 1:]
data = data[1:, 1:].astype(np.float32)
print(data.shape)
data = tf.constant(data)
cov = tf.linalg.matmul(tf.transpose(data), data) / (data.shape[0] - 1)

(288, 512)


In [74]:
import imp
sampling = imp.reload(sampling)

In [80]:
w = np.arange(1, 500.)
w /= w.sum()
w

array([8.01603206e-06, 1.60320641e-05, 2.40480962e-05, 3.20641283e-05,
       4.00801603e-05, 4.80961924e-05, 5.61122244e-05, 6.41282565e-05,
       7.21442886e-05, 8.01603206e-05, 8.81763527e-05, 9.61923848e-05,
       1.04208417e-04, 1.12224449e-04, 1.20240481e-04, 1.28256513e-04,
       1.36272545e-04, 1.44288577e-04, 1.52304609e-04, 1.60320641e-04,
       1.68336673e-04, 1.76352705e-04, 1.84368737e-04, 1.92384770e-04,
       2.00400802e-04, 2.08416834e-04, 2.16432866e-04, 2.24448898e-04,
       2.32464930e-04, 2.40480962e-04, 2.48496994e-04, 2.56513026e-04,
       2.64529058e-04, 2.72545090e-04, 2.80561122e-04, 2.88577154e-04,
       2.96593186e-04, 3.04609218e-04, 3.12625251e-04, 3.20641283e-04,
       3.28657315e-04, 3.36673347e-04, 3.44689379e-04, 3.52705411e-04,
       3.60721443e-04, 3.68737475e-04, 3.76753507e-04, 3.84769539e-04,
       3.92785571e-04, 4.00801603e-04, 4.08817635e-04, 4.16833667e-04,
       4.24849699e-04, 4.32865731e-04, 4.40881764e-04, 4.48897796e-04,
      

In [82]:
%timeit sampling.weighted_choice(tf.constant(w, tf.float32), (10, 5))

1.56 ms ± 92.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [83]:
from l0pca import svd_metric

In [109]:
import imp
svd_metric = imp.reload(svd_metric)

In [110]:
svd_metric.evaluate_cov_eigh(cov, tf.ones_like(cov[0]))

(<tf.Tensor: shape=(), dtype=float32, numpy=1.7891396>,
 <tf.Tensor: shape=(52,), dtype=int32, numpy=
 array([  0,   0,   0,   1,   8,  13,  42,  52,  73,  82,  99, 100, 111,
        117, 125, 135, 136, 138, 142, 144, 150, 157, 174, 180, 205, 208,
        215, 219, 220, 226, 227, 257, 261, 288, 298, 308, 332, 341, 351,
        356, 361, 366, 373, 375, 389, 427, 434, 456, 462, 465, 476, 490],
       dtype=int32)>,
 <tf.Tensor: shape=(52,), dtype=float32, numpy=
 array([0.06742446, 0.06742446, 0.06742446, 0.08337875, 0.10178611,
        0.09459829, 0.0382796 , 0.09640654, 0.10188601, 0.0516508 ,
        0.08892824, 0.04675331, 0.06737258, 0.05553846, 0.0344473 ,
        0.06841697, 0.06865755, 0.09395058, 0.01926947, 0.03386292,
        0.03928844, 0.01909231, 0.10881519, 0.03290281, 0.02074062,
        0.14250293, 0.05595656, 0.04830682, 0.07283236, 0.06237784,
        0.01934316, 0.02940323, 0.05736376, 0.0404963 , 0.02714559,
        0.08541319, 0.14947498, 0.081108  , 0.11351475, 0.0