In [73]:
import numpy as np
np.set_printoptions(precision = 3, linewidth = 80, suppress = True)

In [100]:
n = 5
np.random.seed(4)
A = np.diag(np.random.uniform(-1, 1, n))
A[:, -1] = np.random.uniform(-1, 1, n)
A = A.T.dot(A)
A

array([[ 0.872,  0.   ,  0.   ,  0.   , -0.53 ],
       [ 0.   ,  0.009,  0.   ,  0.   ,  0.09 ],
       [ 0.   ,  0.   ,  0.894,  0.   , -0.934],
       [ 0.   ,  0.   ,  0.   ,  0.185, -0.212],
       [-0.53 ,  0.09 , -0.934, -0.212,  2.466]])

In [172]:
M = np.eye(5)
M[1, 1] = np.cos(1)
M[1, -1] = -np.sin(1)
M[-1, 1] = np.sin(1)
M[-1, -1] = np.cos(1)
M.dot(A).dot(M.T)

array([[ 0.872,  0.446,  0.   ,  0.   , -0.287],
       [ 0.446,  1.667,  0.786,  0.179, -1.155],
       [ 0.   ,  0.786,  0.894,  0.   , -0.504],
       [ 0.   ,  0.179,  0.   ,  0.185, -0.115],
       [-0.287, -1.155, -0.504, -0.115,  0.808]])

In [201]:
M = np.eye(n)
M[0, -1] = -A[0, -1] / A[-1, -1]
M[0, 1] = -M[0, -1] * A[-1, 1] / A[1, 1]
M[0, 2] = -M[0, -1] * A[-1, 2] / A[2, 2]
M[0, 3] = -M[0, -1] * A[-1, 3] / A[3, 3]
M[0, 1:] *= 7.27
M.dot(A)
M.dot(A).dot(np.linalg.inv(M))

array([[ 0.043,  0.681, -0.071, -0.078, -0.067],
       [ 0.   ,  0.009,  0.   ,  0.   ,  0.09 ],
       [ 0.   ,  0.   ,  0.894,  0.   , -0.934],
       [ 0.   ,  0.   ,  0.   ,  0.185, -0.212],
       [-0.53 , -8.272, -0.067,  0.741,  3.295]])

In [267]:
M = np.eye(n)
M[0, 1] = 0.2
M[0, 2] = 1.7
M[0, 3] = -1.
M[0, 4] = 0.9
A2 =M.dot(A).dot(np.linalg.inv(M))
A2

array([[ 0.395,  0.004,  0.007,  0.02 , -0.023],
       [ 0.   ,  0.009,  0.   ,  0.   ,  0.09 ],
       [ 0.   ,  0.   ,  0.894,  0.   , -0.934],
       [ 0.   ,  0.   ,  0.   ,  0.185, -0.212],
       [-0.53 ,  0.196, -0.032, -0.743,  2.943]])

In [287]:
M2 = np.eye(n)
M2[1, 2] = 0.01
M2[1, 3] = -0.05
M2[1, 4] = -0.015
A3 = M2.dot(A2).dot(np.linalg.inv(M2))
A3

array([[ 0.395,  0.004,  0.007,  0.02 , -0.023],
       [ 0.008,  0.006,  0.009,  0.002,  0.047],
       [ 0.   ,  0.   ,  0.894,  0.   , -0.934],
       [ 0.   ,  0.   ,  0.   ,  0.185, -0.212],
       [-0.53 ,  0.196, -0.034, -0.733,  2.946]])

In [288]:
np.linalg.eig(A)[0]

array([3.024, 0.878, 0.39 , 0.133, 0.   ])

In [289]:
np.linalg.eig(A3)[0]

array([3.024, 0.878, 0.39 , 0.133, 0.   ])

In [170]:
np.dot([[1, 0, 0, 0, 1], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]], A)

array([[ 0.342,  0.09 , -0.934, -0.212,  1.936],
       [ 0.   ,  0.009,  0.   ,  0.   ,  0.09 ],
       [ 0.   ,  0.   ,  0.894,  0.   , -0.934],
       [ 0.   ,  0.   ,  0.   ,  0.185, -0.212],
       [-0.53 ,  0.09 , -0.934, -0.212,  2.466]])

In [55]:
M[0, -1] / np.linalg.norm([M[0, -1], M[-1, -1]])

-0.5623100214072791

In [56]:
M.dot(A).dot(np.linalg.inv(M))

array([[ 0.934,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.009],
       [ 0.   ,  0.094,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.13 ],
       [ 0.   ,  0.   ,  0.945,  0.   ,  0.   ,  0.   ,  0.   ,  0.559],
       [ 0.   ,  0.   ,  0.   ,  0.43 ,  0.   ,  0.   ,  0.   , -0.605],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.395,  0.   ,  0.   ,  0.726],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.568,  0.   ,  0.967],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.953, -0.672],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.195]])

In [61]:
M2 = np.eye(8)
M2[1, -1] = 1.25
M2.dot(M).dot(A).dot(np.linalg.inv(M).dot(np.linalg.inv(M2)))

array([[ 0.934,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.009],
       [ 0.   ,  0.094,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.005],
       [ 0.   ,  0.   ,  0.945,  0.   ,  0.   ,  0.   ,  0.   ,  0.559],
       [ 0.   ,  0.   ,  0.   ,  0.43 ,  0.   ,  0.   ,  0.   , -0.605],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.395,  0.   ,  0.   ,  0.726],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.568,  0.   ,  0.967],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.953, -0.672],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.195]])

In [62]:
np.linalg.eigh(A)[0]

array([-0.568,  0.094,  0.195,  0.395,  0.43 ,  0.934,  0.945,  0.953])

In [174]:
M = np.eye(7)
M[0, 1:] = np.random.uniform(-1, 1, 6)
M + np.linalg.inv(M)

array([[2., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 2.]])