In [3]:
import numpy as np
np.set_printoptions(linewidth = 150, precision = 5, suppress = True)

In [5]:
n = 5
np.random.seed(4)
A = np.diag(np.random.uniform(-1., 1., n))
A[:, -1] = np.random.uniform(-1., 1., n)
A

array([[ 0.93406,  0.     ,  0.     ,  0.     , -0.56782],
       [ 0.     ,  0.09446,  0.     ,  0.     ,  0.95255],
       [ 0.     ,  0.     ,  0.94537,  0.     , -0.98754],
       [ 0.     ,  0.     ,  0.     ,  0.42963, -0.49404],
       [ 0.     ,  0.     ,  0.     ,  0.     , -0.13042]])

In [37]:
diag = np.full(n, np.nan)
off_diag = np.full(n - 1, np.nan)

In [38]:
beta = 0.
v = np.asarray([1., 0., 0., 0., 0.])[:, None]
u = np.zeros_like(v)

In [39]:
u = A.dot(v) - beta*u
alpha = np.linalg.norm(u)
diag[0] = alpha
u /= alpha
v = A.T.dot(u) - alpha*v
beta = np.linalg.norm(v)
off_diag[0] = beta
v /= beta
u, alpha, v, beta

(array([[1.],
        [0.],
        [0.],
        [0.],
        [0.]]),
 0.9340596780273533,
 array([[ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [-1.]]),
 0.5678210088392472)

In [29]:
u = A.dot(v) - beta*u
alpha = np.linalg.norm(u)
diag[1] = alpha
u /= alpha
v = A.T.dot(u) - alpha*v
beta = np.linalg.norm(v)
off_diag[1] = beta
v /= beta
u, v

(array([[ 0.     ],
        [-0.65059],
        [ 0.67449],
        [ 0.33743],
        [ 0.08907]]),
 array([[ 0.     ],
        [-0.09357],
        [ 0.97084],
        [ 0.22072],
        [ 0.     ]]))

In [30]:
u = A.dot(v) - beta*u
alpha = np.linalg.norm(u)
diag[2] = alpha
u /= alpha
v = A.T.dot(u) - alpha*v
beta = np.linalg.norm(v)
off_diag[2] = beta
v /= beta
u, v

(array([[ 0.     ],
        [ 0.64567],
        [ 0.73259],
        [-0.19563],
        [-0.09027]]),
 array([[ 0.     ],
        [ 0.45849],
        [ 0.23881],
        [-0.85601],
        [-0.     ]]))

In [31]:
u = A.dot(v) - beta*u
alpha = np.linalg.norm(u)
diag[3] = alpha
u /= alpha
v = A.T.dot(u) - alpha*v
beta = np.linalg.norm(v)
off_diag[3] = beta
v /= beta
u, v

(array([[ 0.     ],
        [-0.37304],
        [ 0.09153],
        [-0.92065],
        [ 0.0698 ]]),
 array([[ 0.     ],
        [-0.88376],
        [ 0.0211 ],
        [-0.46746],
        [-0.     ]]))

In [32]:
diag[-1] = np.linalg.norm(A.dot(v) - beta*u)

In [33]:
B = np.diag(diag)
B[range(n - 1), range(1, n)] = off_diag
B

array([[0.93406, 0.56782, 0.     , 0.     , 0.     ],
       [0.     , 1.46413, 0.6568 , 0.     , 0.     ],
       [0.     , 0.     , 0.64811, 0.2653 , 0.     ],
       [0.     , 0.     , 0.     , 0.34309, 0.21787],
       [0.     , 0.     , 0.     , 0.     , 0.01537]])

In [35]:
np.allclose(np.linalg.svd(B)[1], np.linalg.svd(A)[1])

True