In [1]:
import numpy as np
np.set_printoptions(precision = 3, linewidth = 150, suppress = True)

In [59]:
n = 7
np.random.seed(4)
A_diag = np.diag(np.random.uniform(-1, 1, n))
data = np.random.uniform(-1, 1, n)
A = A_diag + data[:, None].dot(data[None, :])
np.linalg.eigh(A)[0]

array([-0.425,  0.142,  0.412,  0.551,  0.943,  0.946,  3.99 ])

In [49]:
v1 = data * data[0]
# Ignore the diagonal A_diag
v1[0] = 0
v1[1] += (1. if v1[1] >= 0 else -1.) * np.linalg.norm(v1)
# v1[1] += 1. if v1[1] >= 0 else -1.
v1 /= np.linalg.norm(v1)
M = np.eye(n) - 2 * v1[:, None].dot(v1[None, :])
v1

array([ 0.   ,  0.812,  0.052, -0.222,  0.24 , -0.289, -0.384])

In [50]:
M

array([[ 1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   , -0.319, -0.084,  0.361, -0.39 ,  0.469,  0.624],
       [ 0.   , -0.084,  0.995,  0.023, -0.025,  0.03 ,  0.04 ],
       [ 0.   ,  0.361,  0.023,  0.901,  0.107, -0.128, -0.171],
       [ 0.   , -0.39 , -0.025,  0.107,  0.885,  0.139,  0.185],
       [ 0.   ,  0.469,  0.03 , -0.128,  0.139,  0.834, -0.222],
       [ 0.   ,  0.624,  0.04 , -0.171,  0.185, -0.222,  0.705]])

In [51]:
(np.eye(n) - 2 * v1[:, None].dot(v1[None, :])).dot(data[:, None]).dot(data[None, :]).dot(np.eye(n) - 2 * v1[:, None].dot(v1[None, :]))

array([[ 0.975, -1.53 , -0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [-1.53 ,  2.401,  0.   ,  0.   , -0.   , -0.   , -0.   ],
       [-0.   ,  0.   , -0.   ,  0.   ,  0.   , -0.   , -0.   ],
       [-0.   ,  0.   , -0.   ,  0.   ,  0.   , -0.   , -0.   ],
       [-0.   ,  0.   , -0.   ,  0.   ,  0.   , -0.   , -0.   ],
       [ 0.   , -0.   , -0.   , -0.   , -0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ]])

In [52]:
(np.eye(n) - 2 * v1[:, None].dot(v1[None, :])).dot(A_diag).dot(np.eye(n) - 2 * v1[:, None].dot(v1[None, :]))

array([[ 0.934,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.379, -0.053,  0.043, -0.033, -0.411,  0.401],
       [ 0.   , -0.053,  0.937,  0.022, -0.023, -0.001,  0.059],
       [ 0.   ,  0.043,  0.022,  0.385,  0.045,  0.07 , -0.167],
       [ 0.   , -0.033, -0.023,  0.045,  0.351, -0.08 ,  0.174],
       [ 0.   , -0.411, -0.001,  0.07 , -0.08 , -0.311,  0.004],
       [ 0.   ,  0.401,  0.059, -0.167,  0.174,  0.004,  0.51 ]])

In [53]:
diag1 = M.dot(A_diag).dot(M[:, 1:2])
v2 = diag1.copy()[:, 0]
# Ignore the diagonal A_diag
v2[0:2] = 0
v2[2] += (1. if v2[1] >= 0 else -1.) * np.linalg.norm(v2)
v2 /= np.linalg.norm(v2)
M2 = np.eye(n) - 2 * v2[:, None].dot(v2[None, :])
v2

array([ 0.   ,  0.   ,  0.674,  0.055, -0.043, -0.527,  0.514])

In [56]:
np.allclose(M2.dot(M).T, M.dot(M2))

True

In [60]:
np.sort(np.linalg.eig(M2.dot(M).dot(A).dot(M).dot(M2))[0])

array([-0.425,  0.142,  0.412,  0.551,  0.943,  0.946,  3.99 ])