In [1]:
import numpy as np
np.set_printoptions(precision = 5, linewidth = 150, suppress = True)

In [67]:
n = 7
np.random.seed(6)
S = np.diag(np.random.uniform(-1, 1, n))
S[:, -1] = np.random.uniform(-1, 1, n)
S[0, 0] = 0.2
S[0, -1] = 5
S

array([[ 0.2    ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  5.     ],
       [ 0.     , -0.33604,  0.     ,  0.     ,  0.     ,  0.     , -0.32918],
       [ 0.     ,  0.     ,  0.64246,  0.     ,  0.     ,  0.     ,  0.24504],
       [ 0.     ,  0.     ,  0.     , -0.91661,  0.     ,  0.     , -0.12372],
       [ 0.     ,  0.     ,  0.     ,  0.     , -0.78469,  0.     ,  0.47176],
       [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.1901 ,  0.03607],
       [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.15772]])

In [71]:
S.T.dot(S)
np.linalg.norm(np.diagonal(S.T.dot(S)))

25.4574258424205

In [72]:
S[0, 0] ** 2, S[0, 0] * S[0, -1]

(0.04000000000000001, 1.0)

In [80]:
phi = np.arctan(2 * (S.T.dot(S))[0, -1] / ((S.T.dot(S))[-1,-1] - (S.T.dot(S))[0, 0])) / 2
phi, np.sin(phi), np.cos(phi)

(0.03930064937796555, 0.039290533248248855, 0.9992278288744105)

In [76]:
Q = np.eye(n)
Q[0, 0] = np.cos(phi)
Q[0, -1] = np.sin(phi)
Q[-1, 0] = -np.sin(phi)
Q[-1, -1] = np.cos(phi)
np.linalg.norm(np.diagonal(Q.dot(S.T).dot(S).dot(Q.T)))

25.340281256007746

In [81]:
Q.dot(S.T)

array([[ 0.3963 , -0.01293,  0.00963, -0.00486,  0.01854,  0.00142,  0.0062 ],
       [ 0.     , -0.33604,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ],
       [ 0.     ,  0.     ,  0.64246,  0.     ,  0.     ,  0.     ,  0.     ],
       [ 0.     ,  0.     ,  0.     , -0.91661,  0.     ,  0.     ,  0.     ],
       [ 0.     ,  0.     ,  0.     ,  0.     , -0.78469,  0.     ,  0.     ],
       [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.1901 ,  0.     ],
       [ 4.98828, -0.32893,  0.24485, -0.12362,  0.4714 ,  0.03604,  0.1576 ]])

In [78]:
S.T.dot(S)

array([[ 0.04   ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  1.     ],
       [ 0.     ,  0.11292,  0.     ,  0.     ,  0.     ,  0.     ,  0.11062],
       [ 0.     ,  0.     ,  0.41275,  0.     ,  0.     ,  0.     ,  0.15743],
       [ 0.     ,  0.     ,  0.     ,  0.84017,  0.     ,  0.     ,  0.1134 ],
       [ 0.     ,  0.     ,  0.     ,  0.     ,  0.61573,  0.     , -0.37019],
       [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.03614,  0.00686],
       [ 1.     ,  0.11062,  0.15743,  0.1134 , -0.37019,  0.00686, 25.43245]])

In [77]:
Q.dot(S.T).dot(S).dot(Q.T)

array([[ 0.15772,  0.00435,  0.00619,  0.00446, -0.01454,  0.00027,  1.99383],
       [ 0.00435,  0.11292,  0.     ,  0.     ,  0.     ,  0.     ,  0.11053],
       [ 0.00619,  0.     ,  0.41275,  0.     ,  0.     ,  0.     ,  0.15731],
       [ 0.00446,  0.     ,  0.     ,  0.84017,  0.     ,  0.     ,  0.11331],
       [-0.01454,  0.     ,  0.     ,  0.     ,  0.61573,  0.     , -0.3699 ],
       [ 0.00027,  0.     ,  0.     ,  0.     ,  0.     ,  0.03614,  0.00685],
       [ 1.99383,  0.11053,  0.15731,  0.11331, -0.3699 ,  0.00685, 25.31473]])

In [64]:
np.tan(phi * 2)

-0.1550887399328767

In [65]:
2 * (S.T.dot(S))[0, -1] / ((S.T.dot(S))[-1,-1] - (S.T.dot(S))[0, 0])

-0.1550887399328767